"""Change default surname

Revision ID: 38347d8f2e1a
Revises: 50139d5e93ab
Create Date: 2021-09-08 11:36:01.899460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38347d8f2e1a'
down_revision = '50139d5e93ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author_model', 'middle_name')
    op.drop_column('quote_model', 'rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_model', sa.Column('rate', sa.INTEGER(), nullable=True))
    op.add_column('author_model', sa.Column('middle_name', sa.VARCHAR(length=32), nullable=True))
    # ### end Alembic commands ###
