"""add surname

Revision ID: 8900a9753047
Revises: 0cab0aef4ee0
Create Date: 2021-09-06 19:52:30.888260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8900a9753047'
down_revision = '0cab0aef4ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_model', sa.Column('surname', sa.String(length=32), server_default='Иванов', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author_model', 'surname')
    # ### end Alembic commands ###
