"""Add rating

Revision ID: cd1f7920bd4a
Revises: 38347d8f2e1a
Create Date: 2021-09-08 14:42:18.791009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1f7920bd4a'
down_revision = '38347d8f2e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_model', sa.Column('rate', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote_model', 'rate')
    # ### end Alembic commands ###
